package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tag implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String category;

	public tag() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public tag(java.lang.String category) {
		this.category = category;
	}

}